### ISSUE TITLE
Parallax Box Image Serving

### ISSUE THREAD

**Issue by baronvonvaderham** [AASHE/aashe-conference#1]
Currently, the parallax box div defines a background attribute that requires a URL be supplied via the url() function. This renders the file address as "localhost://[full file path]", which returns a 404. A GET request for just the full file path without the address prefix is successful and is used everywhere else.

It is required that the url() function be invoked in this attribute, it cannot be bypassed. A way needs to be found to correctly serve files when requested via a full web URL in this way.

**Comment by jessicaaasheaashe** [comment]
@baronvonvaderham @jamstooks Hey guys!  This seems to be the major thing right now holding me up from completing any webpage.  Any idea when this might be prioritized?  It turns out most of the pages I am creating will have the "static banner image".

**Comment by baronvonvaderham** [comment]
Ben is currently on vacation. In the meantime, I mentioned that you can complete those banners and upload the images, they will appear once the display fix is implemented.

**Comment by jessicaaasheaashe** [comment]
Yeah, its hard because I can't see what they look like while I'm building
it.  If the photo doesn't work I can't see to change it.

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Wed, Apr 6, 2016 at 9:52 AM, Scott Johnson <notifications@github.com>
wrote:

> Ben is currently on vacation. In the meantime, I mentioned that you can
> complete those banners and upload the images, they will appear once the
> display fix is implemented.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/1#issuecomment-206382170>
>

-- 
The AASHE Sustainability Awards are now open! Submit your application 
<http://www.aashe.org/about/aashe-awards> by Friday, June 3 at 5 p.m. ET. 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by baronvonvaderham** [comment]
I found a workaround. The images do NOT scale, so you will need to crop and resize as needed to get them to fit correctly.

**Comment by baronvonvaderham** [comment]
I highly recommend at this time deleting all test images and editing any images you wish to keep to have appropriate names and categories. If we start dumping in banner images like crazy it's going to start getting very disorganized.

**Comment by jessicaaasheaashe** [comment]
Thanks!  Can you tell me the size needed then so I can resize them to fit?

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Wed, Apr 6, 2016 at 10:19 AM, Scott Johnson <notifications@github.com>
wrote:

> I found a workaround. The images do NOT scale, so you will need to crop
> and resize as needed to get them to fit correctly.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/1#issuecomment-206393799>
>

-- 
The AASHE Sustainability Awards are now open! Submit your application 
<http://www.aashe.org/about/aashe-awards> by Friday, June 3 at 5 p.m. ET. 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by jessicaaasheaashe** [comment]
Yay!!!! I'm glad you figured it out!

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Wed, Apr 6, 2016 at 10:19 AM, Scott Johnson <notifications@github.com>
wrote:

> I found a workaround. The images do NOT scale, so you will need to crop
> and resize as needed to get them to fit correctly.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/1#issuecomment-206393799>
>

-- 
The AASHE Sustainability Awards are now open! Submit your application 
<http://www.aashe.org/about/aashe-awards> by Friday, June 3 at 5 p.m. ET. 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by jessicaaasheaashe** [comment]
OK...Do I just delete all of the ones in the Demo category?

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Wed, Apr 6, 2016 at 10:22 AM, Scott Johnson <notifications@github.com>
wrote:

> I highly recommend at this time deleting all test images and editing any
> images you wish to keep to have appropriate names and categories. If we
> start dumping in banner images like crazy it's going to start getting very
> disorganized.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/1#issuecomment-206396511>
>

-- 
The AASHE Sustainability Awards are now open! Submit your application 
<http://www.aashe.org/about/aashe-awards> by Friday, June 3 at 5 p.m. ET. 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by baronvonvaderham** [comment]
I actually have no idea on sizing, you'll have to experiment a little bit to see what works.

Parallax Boxes actually tile the image, so if you choose a small one like a logo it repeats in a pattern. That's what they do on the Unify example with the faces. The banners are just static, so you'll want to crop to the same size it is on your screen.

Not sure about the images, you've been doing more in there than I have. Basically anything you didn't put in there from prod with the intention of it being permanent I would delete, and anything you want to keep edit it to add a "caption" (title) and appropriate categories. I prepopulated a few useful ones but feel free to create more categories so hopefully down the line we can filter the available image choices in dropdowns based on these.

**Comment by jessicaaasheaashe** [comment]
I added an image to this page and it is not appearing:
http://aashe-conference-prod.herokuapp.com/registration/

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Wed, Apr 6, 2016 at 10:28 AM, Scott Johnson <notifications@github.com>
wrote:

> I actually have no idea on sizing, you'll have to experiment a little bit
> to see what works.
>
> Parallax Boxes actually tile the image, so if you choose a small one like
> a logo it repeats in a pattern. That's what they do on the Unify example
> with the faces. The banners are just static, so you'll want to crop to the
> same size it is on your screen.
>
> Not sure about the images, you've been doing more in there than I have.
> Basically anything you didn't put in there from prod with the intention of
> it being permanent I would delete, and anything you want to keep edit it to
> add a "caption" (title) and appropriate categories. I prepopulated a few
> useful ones but feel free to create more categories so hopefully down the
> line we can filter the available image choices in dropdowns based on these.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/1#issuecomment-206400485>
>

-- 
The AASHE Sustainability Awards are now open! Submit your application 
<http://www.aashe.org/about/aashe-awards> by Friday, June 3 at 5 p.m. ET. 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by baronvonvaderham** [comment]
Of course it would break in production because we're using S3 storage. Going to have to wait for Ben on this one, I'm out of tricks and he's the one who designed that system.
