### ISSUE TITLE
Embed Your Tube Video

### ISSUE THREAD

**Issue by jessicaaasheaashe** [AASHE/aashe-conference#100]
@baronvonvaderham If possible, we'd like to embed a YouTube video on this rich text page: http://aashe-conference-prod.herokuapp.com/about/sustainability/.  You'll see I put the embed code on the page where I'd the video to be placed.  Is this possible?

**Comment by jessicaaasheaashe** [comment]
@baronvonvaderham Actually, if I could make the right column image the video, that would work too.

**Comment by baronvonvaderham** [comment]
Ok, I will just enable the video content type for that template region.
