### ISSUE TITLE
Cell padding

### ISSUE THREAD

**Issue by jessicaaasheaashe** [AASHE/aashe-conference#101]
@baronvonvaderham I have placed the image in this rich text content in a table so I could align it to the right and have text wrap around it.  However, I am unable to use cell padding so the text doesn't go so close to the edge of the image.  Could you tell me how to fix? There are probably other pages where this occurs also. 

http://aashe-conference-prod.herokuapp.com/news-media/press-release-1/

**Comment by baronvonvaderham** [comment]
Hmmm, that is odd. It has the correct properties in the html document, but the text is in <p> tags that extend the full page width.

The best recommendation I could make would be something like extending the table to include the text. I suspect it's not respecting the cell padding because it's not itself a cell. Something like a big full width row for your opening text, two columns for where the image is present, then back to full width at the bottom.

A tiny bit laborious to set up, but would get the job done.

I tried modifying the table properties, there's a "style" tab, so I added the css property "padding: 20px;" and it affected nothing. This pretty well confirmed for me that the text needs to be part of the table for them to interact properly.

**Comment by jessicaaasheaashe** [comment]
@baronvonvaderham I tried putting the text inside the table and it skews the text all the left: http://aashe-conference-prod.herokuapp.com/news-media/press-release-marcedwards/

**Comment by baronvonvaderham** [comment]
Right. You'll need 4 regions. Full width top row (first lines of text above image), two columns below that (left text, right image), then full width bottom row (text below image). Let me play with that page and see if I can get it right as an example.

**Comment by jessicaaasheaashe** [comment]
@baronvonvaderham Also want to note that we don't seem to having that problem on this page with the same layout: http://aashe-conference-prod.herokuapp.com/news-media/press-release-3/

**Comment by baronvonvaderham** [comment]
OH! I see the problem now :)

You're using a Title Box content type in the Marc Edwards page. On the other page you're using an actual RichText content type.

**Comment by baronvonvaderham** [comment]
I have it set up to work using a 4 cell table currently, but feel free to copy/paste that content into a RichText block instead and you should also be fine there.

**Comment by baronvonvaderham** [comment]
Never mind, I just did it. All fixed!

**Comment by jessicaaasheaashe** [comment]
Thank you! Looks much better!

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Tue, Apr 26, 2016 at 4:39 PM, Scott Johnson <notifications@github.com>
wrote:

> Never mind, I just did it. All fixed!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/101#issuecomment-214878707>
>

-- 
The AASHE Sustainability Awards are now open! Submit your application 
<http://www.aashe.org/about/aashe-awards> by Friday, June 3 at 5 p.m. ET. 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by jessicaaasheaashe** [comment]
@baronvonvaderham Now I'm confused.  I don't see the 4 cell table you are referrring to in the Marc Edwards press release?  I need to fix this page too: http://aashe-conference-prod.herokuapp.com/news-media/press-release-1/

**Comment by baronvonvaderham** [comment]
Yeah I got rid of it. Once I realized it was in the wrong content type, you don't need that anymore, you can do it exactly like the other pages where you just embed the image as a single cell table aligned to the right.

**Comment by jessicaaasheaashe** [comment]
So that's what I think I have for this page:
http://aashe-conference-prod.herokuapp.com/news-media/press-release-1/  but
it doesn't seem to be working?

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Tue, Apr 26, 2016 at 4:54 PM, Scott Johnson <notifications@github.com>
wrote:

> Yeah I got rid of it. Once I realized it was in the wrong content type,
> you don't need that anymore, you can do it exactly like the other pages
> where you just embed the image as a single cell table aligned to the right.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/101#issuecomment-214882814>
>

-- 
The AASHE Sustainability Awards are now open! Submit your application 
<http://www.aashe.org/about/aashe-awards> by Friday, June 3 at 5 p.m. ET. 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by baronvonvaderham** [comment]
Yeah, that one's correct but displaying oddly, working on it now.

**Comment by baronvonvaderham** [comment]
Fixed. You can just stretch the table border a tiny bit, then select the image only and click the button to align right. That creates a little bit of a buffer within the cell. I think the other images/tables have that unintentionally and this one just happened to be minimized to exactly the image size.

**Comment by jessicaaasheaashe** [comment]
Thank you!

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Tue, Apr 26, 2016 at 4:57 PM, Scott Johnson <notifications@github.com>
wrote:

> Fixed. You can just stretch the table border a tiny bit, then select the
> image only and click the button to align right. That creates a little bit
> of a buffer within the cell. I think the other images/tables have that
> unintentionally and this one just happened to be minimized to exactly the
> image size.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/101#issuecomment-214883909>
>

-- 
The AASHE Sustainability Awards are now open! Submit your application 
<http://www.aashe.org/about/aashe-awards> by Friday, June 3 at 5 p.m. ET. 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>
