### ISSUE TITLE
Add additional icons

### ISSUE THREAD

**Issue by baronvonvaderham** [AASHE/aashe-conference#102]
https://docs.google.com/document/d/1F1sx89U8d-1s9EzI7a62IazKHNknte4livqjVhZQXcE/edit?ts=571fb9fa

**Comment by jessicaaasheaashe** [comment]
@baronvonvaderham When I select icons and then try to save I get an error: 
![image](https://cloud.githubusercontent.com/assets/18149121/14835540/42c9f686-0bd8-11e6-9449-088db591ad27.png)

**Comment by baronvonvaderham** [comment]
ALTER TABLE page_page_featuredpane ALTER COLUMN icon TYPE character varying(1032);

Just saving this command here so I don't lose it. The issue is that for some bizarre reason, running a syncdb on heroku isn't altering the size of that attribute in the database (the original limit was 10 characters, and these new ones are considerably longer). I don't understand why, but I can fix it by manually changing the parameters with that command.

**Comment by baronvonvaderham** [comment]
Fixed. Tested on that exact page with 3 random selections and it works great. Weirdest database glitch ever....
