### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by jessicaaasheaashe** [AASHE/aashe-conference#103]
@baronvonvaderham I have been getting an application error for the past hour and have been unable to update the website.  Could you look into it?

**Comment by baronvonvaderham** [comment]
I can't duplicate this, everything looks fine.

**Comment by jessicaaasheaashe** [comment]
Seems to be working again.

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Thu, Apr 28, 2016 at 12:27 PM, Scott Johnson <notifications@github.com>
wrote:

> I can't duplicate this, everything looks fine.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/103#issuecomment-215485510>
>

-- 
The AASHE Sustainability Awards are now open! Submit your application 
<http://www.aashe.org/about/aashe-awards> by Friday, June 3 at 5 p.m. ET. 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>
