### ISSUE TITLE
Contact Us links not working

### ISSUE THREAD

**Issue by jessicaaasheaashe** [AASHE/aashe-conference#107]
@baronvonvaderham The contact us links in the header and footer don't seem to be working.  When I click on them, nothing happens.

**Comment by jessicaaasheaashe** [comment]
In fact, it doesn't seem like any of the mailto: links are working.

**Comment by baronvonvaderham** [comment]
Hmmm. They're working fine for me in Linux, Windows, and Mac, and even on my android phone. Do you have an email client configured? It might be your browser preferences that you don't have it set up to associate those links with an email program?

**Comment by jessicaaasheaashe** [comment]
I'm not sure I would know how to set it up?  I use Gmail and Chrome.

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Fri, May 6, 2016 at 12:43 PM, Scott Johnson <notifications@github.com>
wrote:

> Hmmm. They're working fine for me in Linux, Windows, and Mac, and even on
> my android phone. Do you have an email client configured? It might be your
> browser preferences that you don't have it set up to associate those links
> with an email program?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/107#issuecomment-217494282>
>

-- 
The AASHE Sustainability Awards are now open! Submit your application 
<http://www.aashe.org/about/aashe-awards> by Friday, June 3 at 5 p.m. ET. 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by baronvonvaderham** [comment]
Ah ok. Mailto links work with things like Thunderbird or Outlook: https://en.wikipedia.org/wiki/Mailto

If you have one of those installed, then your browser treats those like what we call "magnet links", which are links that don't open a webpage but open an application on your system and perform an action. In this case, they'd be associated with an email client and the action is opening a new email message with certain fields prepopulated.

As far as I know, they don't work with just gmail in a chrome tab.

**Comment by jessicaaasheaashe** [comment]
Ok...so no issue here?

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Fri, May 6, 2016 at 12:52 PM, Scott Johnson <notifications@github.com>
wrote:

> Ah ok. Mailto links work with things like Thunderbird or Outlook:
> https://en.wikipedia.org/wiki/Mailto
>
> If you have one of those installed, then your browser treats those like
> what we call "magnet links", which are links that don't open a webpage but
> open an application on your system and perform an action. In this case,
> they'd be associated with an email client and the action is opening a new
> email message with certain fields prepopulated.
>
> As far as I know, they don't work with just gmail in a chrome tab.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/107#issuecomment-217496572>
>

-- 
The AASHE Sustainability Awards are now open! Submit your application 
<http://www.aashe.org/about/aashe-awards> by Friday, June 3 at 5 p.m. ET. 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by baronvonvaderham** [comment]
Doesn't seem to be. I have a meeting in 5 minutes, I'll ask them to quick test it for me to be sure.

**Comment by jessicaaasheaashe** [comment]
Thank you! It works for Andrea so I'm sure its just my computer.

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Fri, May 6, 2016 at 12:56 PM, Scott Johnson <notifications@github.com>
wrote:

> Doesn't seem to be. I have a meeting in 5 minutes, I'll ask them to quick
> test it for me to be sure.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/107#issuecomment-217497385>
>

-- 
The AASHE Sustainability Awards are now open! Submit your application 
<http://www.aashe.org/about/aashe-awards> by Friday, June 3 at 5 p.m. ET. 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>
