### ISSUE TITLE
Pricing Table Page Breaks

### ISSUE THREAD

**Issue by jamstooks** [AASHE/aashe-conference#110]
It looks like the column count [is hard-coded](https://github.com/AASHE/aashe-conference/blob/master/conference/content/types/pricing_table.py#L19), which means that columns can't be removed without throwing a 500 - IndexError.

I would recommend:

        for x in range(0, len(deadlines)):

**Comment by baronvonvaderham** [comment]
Will fix to make column number dynamic, and also add a strikethrough toggle to allow crossing out a column after a deadline passes rather than removing it.

**Comment by baronvonvaderham** [comment]
Pushing up to dev to test migration needed, waiting on approval from Jessica to deploy to production.
