### ISSUE TITLE
Footer Styling

### ISSUE THREAD

**Issue by baronvonvaderham** [AASHE/aashe-conference#2]
Footer looks weird.It's limited by the same restriction as the rest of the page. The Hub has it at full window width, but I can't figure out how to do that.

Anyway, it's functional and uses the theme properly right now, but could use some love to make it pop more.

**Comment by baronvonvaderham** [comment]
Full width achieved by removing container div from around content. Will re-add to specific content pieces that should be restricted, but should not be imposed by default on the entire content block of base.html.

**Comment by jessicaaasheaashe** [comment]
@baronvonvaderham Could you add "Subscribe to Our Newsletters" in the same font as "Stay Connected" and "Contact Us" and then add this sign up now button in the footer?  Here is the code for the button: 

-------------------------------------
<div align="center"><a href="http://visitor.r20.constantcontact.com/d.jsp?llr=ypfrgybab&amp;p=oi&amp;m=1101397530104&amp;sit=cck9okwbb&amp;f=3e19f712-0e9c-4dfc-a328-8c4423ffb19e" class="button" style="border: 1px solid rgb(91, 91, 91); color: rgb(91, 91, 91); display: inline-block; padding: 8px 10px; text-shadow: none; border-radius: 10px; background-color: rgb(232, 232, 232);">Sign Up Now</a><div id="ctct_button_footer" align="center" style="font-family:Arial,Helvetica,sans-serif;font-size:10px;color:#999999;margin-top: 10px;"></div></div>
-------------------------------------
