### ISSUE TITLE
Host Institution Profile Content Type

### ISSUE THREAD

**Issue by baronvonvaderham** [AASHE/aashe-conference#22]
Create content type that stores all necessary info to construct the full profile page for a host institution.

Duplicate: http://htmlstream.com/preview/unify-v1.8/portfolio_old_item.html

* Name
* Image
* Description
* Contact Info
* Link

**Comment by jessicaaasheaashe** [comment]
@baronvonvaderham I don't think will be necessary afterall.  I've laid out the page as such: http://aashe-conference-prod.herokuapp.com/engage/presidents-welcome/ which I think works fine unless you can think of a better way to layout the content.

**Comment by baronvonvaderham** [comment]
Nope, that looks good to me.
