### ISSUE TITLE
Additional Header Menu

### ISSUE THREAD

**Issue by baronvonvaderham** [AASHE/aashe-conference#29]
We are missing the header menu as noted in the site map doc (https://docs.google.com/document/d/1XU8_7MJ5kO_3t_YvQWhPSq9byCfb2cugdldjzXQ1_q8/edit)

**Comment by baronvonvaderham** [comment]
Links are currently nonfunctional until the pages are made so the URL patterns are known.

**Comment by jessicaaasheaashe** [comment]
How do we edit that menu and the associated pages?

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Tue, Mar 29, 2016 at 8:05 PM, Scott Johnson <notifications@github.com>
wrote:

> Links are currently nonfunctional until the pages are made so the URL
> patterns are known.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/29#issuecomment-203163731>
>

-- 
Check out the new Campus Sustainability Hub <http://hub.aashe.org/>, an 
online library where members can quickly and easily find relevant resources.


Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by baronvonvaderham** [comment]
Those need to be hard-coded in the base template by me, but should not be changing frequently. If a link is something that should be more dynamic, it should be in the drop-down nav bar. The concept of a header bar like this in design is that it is something static and predictable that will always need to be accessible for the lifetime of the site.

The associated pages, however, you create just as you normally would, and then I would replace the placeholder '#' with the appropriate URL patterns.

**Comment by jessicaaasheaashe** [comment]
So when I create a page for them...do I NOT include in navigation and then
just let you know when to link them?

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Wed, Mar 30, 2016 at 11:37 AM, Scott Johnson <notifications@github.com>
wrote:

> Those need to be hard-coded in the base template by me, but should not be
> changing frequently. If a link is something that should be more dynamic, it
> should be in the drop-down nav bar. The concept of a header bar like this
> in design is that it is something static and predictable that will always
> need to be accessible for the lifetime of the site.
>
> The associated pages, however, you create just as you normally would, and
> then I would replace the placeholder '#' with the appropriate URL patterns.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/29#issuecomment-203492649>
>

-- 
Check out the new Campus Sustainability Hub <http://hub.aashe.org/>, an 
online library where members can quickly and easily find relevant resources.


Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by baronvonvaderham** [comment]
It depends. I see we have Contact Us in the navigation, so that's fine. It just depends on what you want....if it makes sense to have the link in two places, go for it, I just wouldn't advise having them in navigation if they're parent pages, only children.

**Comment by baronvonvaderham** [comment]
Otherwise, yes, once you create those pages linked in the top bar, I'll go in and revise the URLs.
