### ISSUE TITLE
TinyMCE Enhancement - Tables

### ISSUE THREAD

**Issue by baronvonvaderham** [AASHE/aashe-conference#31]
Jesssica: "Need the ability to add and image, table, etc in the main content type"

I assume she means "Rich Text", so this is what we had discussed regarding using a customized TinyMCE.

**Comment by baronvonvaderham** [comment]
@jamstooks Tossing this one your way since you had mentioned in a meeting you guys had done this before elsewhere. Or maybe @rerb could do it?

**Comment by jamstooks** [comment]
Scott and I discussed this on our call. He's going to get the js config file running locally and add the tabular thing himself and give the view/template for the image selection option a shot.
