### ISSUE TITLE
Sponsor Logo Sizing

### ISSUE THREAD

**Issue by baronvonvaderham** [AASHE/aashe-conference#32]
Need to find a way to create uniform thumbnails of logo images.

**Comment by baronvonvaderham** [comment]
Fix works locally, but is broken on heroku. 404 Errors when attempting to retrieve thumbnails for some reason.

**Comment by baronvonvaderham** [comment]
Removed AWS_QUERYSTRING_AUTH from settings, which fixed the broken URL strings. However, the 404 not found errors have now become "403 forbidden" errors instead.

**Comment by baronvonvaderham** [comment]
Surrendering on this bug for now. There is something wrong with sorl-thumbnail and this S3 bucket, it kicks a 404 if AWS_QUERYSTRING_AUTH is on, a 403 if it's off. In either case, it will not create new folders or files in S3. It continues to look like a permissions issue, but I'm stumped regarding how to fix it (no other heroku app of ours has this issue and all settings are identical from what I can tell).

At the same time, it does successfully upload and retrieve files via every other part of this site, regardless of the Auth setting, so the server SHOULD have sufficient permissions to do everything.

If @jamstooks or @rerb wants to take a look, I'd welcome another brain on this problem, but I'm going to shelve this on my end and recommend that staff resize the logo images before upload until we can find a solution to this.

**Comment by baronvonvaderham** [comment]
I WIN! I just had a brainwave in the shower. I was thinking about it all wrong. Screw the image files, leave them alone. Why don't I just use a fresh "frame" class wrapped around the image and some CSS trickery?

Add a div around the image but inside the owl-item div. That way the unify theme css still handles everything correctly.

Then I drop the "frame" in with defined dimensions that take up the max size of the owl-item, so it "pushes out" the whole region. Then the image WITHIN that I give an absolute position attribute with top/bottom/left/right = 0, dead center!

It's not pretty, but it works.

**Comment by jessicaaasheaashe** [comment]
Thanks for sharing your shower thoughts! LOL!  You crack me up!
