### ISSUE TITLE
Add Header Bar Text Blocks

### ISSUE THREAD

**Issue by baronvonvaderham** [AASHE/aashe-conference#34]
Add django_block_content bits for additional info text (important dates, etc.). Reformat header bar to fit it.

**Comment by baronvonvaderham** [comment]
Not using django_block_content, that only allows for plain text.

Instead, created a new template region "Header Block" that will be present in all pages (it's in base.html, not any actual layout templates, just like the sponsor bar is now).

It works with a Title Box added in there, but we don't want to have to edit EVERY page when you make a change, so I'm working on a system similar to the sponsor logo set so you can edit one object and have the change trickle down to all pages at once.

**Comment by baronvonvaderham** [comment]
Ran into a snag on this. I've created a region and content type similar to the logo collection, which would allow you to edit a single piece of content just like the logo collection, and the change would trickle down to every page containing that block.

The problem is, the little popup that lets you edit the content piece to add does not have the TinyMCE interface, it only supports plain text.

I found a workaround that allows me to override this and add it using something called a MixIn....however, the module is out of date and needs some work. I'm going to do that work myself and submit a pull request to the creator so I can update it for him (it'll take way too long to request it and wait for him to do it himself). [(Link to repo so I don't lose it)](https://github.com/bmihelac/feincms-feincmsext/blob/master/feincmsext/richtextadmin/admin.py)

So until that happens (might take an hour, might take a month), I'm going to leave things as they are....you can add a Title Box content type (which is really just a rich text block) into the header. This will work exactly the same as what I'm trying to do now, except it will NOT sync across pages. You will have to add a Title Box to each page where you want this to appear in the header and copy/paste the content into each.

Sorry, I know that's a pain to do, but I'd also suggest that perhaps for now you just add stuff to the header in the "main" pages? Then we can go ahead and add more stuff down the road if this sync issue gets solved. The up-side is you could actually have DIFFERENT stuff in that region on each page!

Anyway, that's what's happening with that. All the other changes are done and about to get pushed up, so the header and footer should finally be in order. I'll just replace the logo once we get the new one.

**Comment by jessicaaasheaashe** [comment]
Thanks Scott!  I added some text to the Home Page and its not laying out in
the correct place:

[image: Inline image 1]

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Fri, Apr 1, 2016 at 3:01 PM, Scott Johnson <notifications@github.com>
wrote:

> Ran into a snag on this. I've created a region and content type similar to
> the logo collection, which would allow you to edit a single piece of
> content just like the logo collection, and the change would trickle down to
> every page containing that block.
>
> The problem is, the little popup that lets you edit the content piece to
> add does not have the TinyMCE interface, it only supports plain text.
>
> I found a workaround that allows me to override this and add it using
> something called a MixIn....however, the module is out of date and needs
> some work. I'm going to do that work myself and submit a pull request to
> the creator so I can update it for him (it'll take way too long to request
> it and wait for him to do it himself). (Link to repo so I don't lose it)
> <https://github.com/bmihelac/feincms-feincmsext/blob/master/feincmsext/richtextadmin/admin.py>
>
> So until that happens (might take an hour, might take a month), I'm going
> to leave things as they are....you can add a Title Box content type (which
> is really just a rich text block) into the header. This will work exactly
> the same as what I'm trying to do now, except it will NOT sync across
> pages. You will have to add a Title Box to each page where you want this to
> appear in the header and copy/paste the content into each.
>
> Sorry, I know that's a pain to do, but I'd also suggest that perhaps for
> now you just add stuff to the header in the "main" pages? Then we can go
> ahead and add more stuff down the road if this sync issue gets solved. The
> up-side is you could actually have DIFFERENT stuff in that region on each
> page!
>
> Anyway, that's what's happening with that. All the other changes are done
> and about to get pushed up, so the header and footer should finally be in
> order. I'll just replace the logo once we get the new one.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/34#issuecomment-204524875>
>

-- 
Check out the new Campus Sustainability Hub <http://hub.aashe.org/>, an 
online library where members can quickly and easily find relevant resources.

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by jessicaaasheaashe** [comment]
Disregard last comment.  Added left align tags and it fixed it.

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Fri, Apr 1, 2016 at 2:20 PM, Scott Johnson <notifications@github.com>
wrote:

> Not using django_block_content, that only allows for plain text.
>
> Instead, created a new template region "Header Block" that will be present
> in all pages (it's in base.html, not any actual layout templates, just like
> the sponsor bar is now).
>
> It works with a Title Box added in there, but we don't want to have to
> edit EVERY page when you make a change, so I'm working on a system similar
> to the sponsor logo set so you can edit one object and have the change
> trickle down to all pages at once.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/34#issuecomment-204501323>
>

-- 
Check out the new Campus Sustainability Hub <http://hub.aashe.org/>, an 
online library where members can quickly and easily find relevant resources.

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by baronvonvaderham** [comment]
Did you want this to just be a static layout? Is it only ever going to be just text? (no links or buttons)

If so, I can create a static content type where you'd have fields like "Headline", "text line 1", and "text line 2". Less flexible, but would allow sharing across all pages like the sponsor logo sets. The RichText is what prevents that currently.

**Comment by jessicaaasheaashe** [comment]
Yes, I believe it will only be text.  Otherwise the header could get too
busy.  I created one on the Home page but I didn't copy it over to all of
the other pages yet.

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Mon, Apr 4, 2016 at 1:24 PM, Scott Johnson <notifications@github.com>
wrote:

> Did you want this to just be a static layout? Is it only ever going to be
> just text? (no links or buttons)
>
> If so, I can create a static content type where you'd have fields like
> "Headline", "text line 1", and "text line 2". Less flexible, but would
> allow sharing across all pages like the sponsor logo sets. The RichText is
> what prevents that currently.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/34#issuecomment-205404454>
>

-- 
Check out the new Campus Sustainability Hub <http://hub.aashe.org/>, an 
online library where members can quickly and easily find relevant resources.

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by baronvonvaderham** [comment]
Then I will use that as a template and add a content type that mimics it. Hold off copying for now.

**Comment by baronvonvaderham** [comment]
Commits 6f92c1db381abf91aeb7d00f2c2bc4365c2c84b2 through 2a352e5db114af420813b1e021efb99413fdac8a
