### ISSUE TITLE
Home Button Hover Over Color

### ISSUE THREAD

**Issue by jessicaaasheaashe** [AASHE/aashe-conference#39]
When you hover over the Home tab on the main menu, it is not the same shade of green as the other menu items when you hover over them.

**Comment by jessicaaasheaashe** [comment]
Hey @baronvonvaderham ...I tried to add a "label" to this ticket but it won't let me.  When I hover over labels, it doesn't do anything.

**Comment by baronvonvaderham** [comment]
That's odd....

The color is due to that being just a plain link rather than a menu toggle, but I should be able to override the styling.
