### ISSUE TITLE
Remove Login and Account Links from base template

### ISSUE THREAD

**Issue by jessicaaasheaashe** [AASHE/aashe-conference#40]
Hey!  I don't believe we have any user restricted content or any need (besides AASHE staff) to login on this site.  Is there a need to have the login and my account links in the header menu?

**Comment by baronvonvaderham** [comment]
I agree, it's not totally necessary, but it's a standard piece of the aashe-theme library for uniformity across all of our pages.

**Comment by jessicaaasheaashe** [comment]
Do you think we could consider eliminating it so the rest of the items on
that menu would slide over to the right a little?

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Wed, Mar 30, 2016 at 11:44 AM, Scott Johnson <notifications@github.com>
wrote:

> I agree, it's not totally necessary, but it's a standard piece of the
> aashe-theme library for uniformity across all of our pages.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/40#issuecomment-203496477>
>

-- 
Check out the new Campus Sustainability Hub <http://hub.aashe.org/>, an 
online library where members can quickly and easily find relevant resources.


Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by baronvonvaderham** [comment]
I'll defer to @jamstooks on that one if he can weigh in.

**Comment by jamstooks** [comment]
I think we can remove the login items for sure, but I would recommend keeping all the other stylings consistent with the hub and theme for now.

Your base template should be able to simply override that block that's inherited from aashe-theme.
