### ISSUE TITLE
Flickr gallery integration

### ISSUE THREAD

**Issue by baronvonvaderham** [AASHE/aashe-conference#42]
Add embedded flickr gallery content type

**Comment by baronvonvaderham** [comment]
Completed, just waiting on appropriate flickr embed code to test with (code I got via email only embedded the one image, not the gallery).

**Comment by jessicaaasheaashe** [comment]
Is this the embed coded you need:


Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Thu, Mar 31, 2016 at 5:12 PM, Scott Johnson <notifications@github.com>
wrote:

> Completed, just waiting on appropriate flickr embed code to test with
> (code I got via email only embedded the one image, not the gallery).
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/42#issuecomment-204131305>
>

-- 
Check out the new Campus Sustainability Hub <http://hub.aashe.org/>, an 
online library where members can quickly and easily find relevant resources.


Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by baronvonvaderham** [comment]
Probably, but github filters out raw html :)

Try it out! Create a flickr gallery page (new template is up there) and drop a raw content into the gallery region. Paste it there and see what happens.

However, it might be what Andrea gave me earlier. You need to get it from the slideshow page specifically (normal gallery url + '/show').

**Comment by jessicaaasheaashe** [comment]
I did it!  http://aashe-conference-prod.herokuapp.com/gallery/



Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Thu, Mar 31, 2016 at 6:17 PM, Scott Johnson <notifications@github.com>
wrote:

> Probably, but github filters out raw html :)
>
> Try it out! Create a flickr gallery page (new template is up there) and
> drop a raw content into the gallery region. Paste it there and see what
> happens.
>
> However, it might be what Andrea gave me earlier. You need to get it from
> the slideshow page specifically (normal gallery url + '/show').
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/42#issuecomment-204154447>
>

-- 
Check out the new Campus Sustainability Hub <http://hub.aashe.org/>, an 
online library where members can quickly and easily find relevant resources.


Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by baronvonvaderham** [comment]
Awesome. Yeah that's what we needed, embeds the whole slideshow.

I can't tweak the size, but there might be some parameters in the embed code that specify that which you can play with to see if you can make it bigger or whatever.

**Comment by jessicaaasheaashe** [comment]
I did that. It was default at 400 x 300 and I made it 600 x 450 by changing
the code.  Thanks!

OK...I'm tired so I won't bother you anymore tonight.  Have a good night!

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Thu, Mar 31, 2016 at 6:42 PM, Scott Johnson <notifications@github.com>
wrote:

> Awesome. Yeah that's what we needed, embeds the whole slideshow.
>
> I can't tweak the size, but there might be some parameters in the embed
> code that specify that which you can play with to see if you can make it
> bigger or whatever.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/42#issuecomment-204160415>
>

-- 
Check out the new Campus Sustainability Hub <http://hub.aashe.org/>, an 
online library where members can quickly and easily find relevant resources.


Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>
