### ISSUE TITLE
Add "Title" Content type to allow adding headers to regions without containers

### ISSUE THREAD

**Issue by jessicaaasheaashe** [AASHE/aashe-conference#43]
I added a rich text content type in the features section and it is aligning to the right when it should align to the left. 

I added rich text content type above in Sponsors area and it aligning way to the left and not aligned with other content.  

![image](https://cloud.githubusercontent.com/assets/18149121/14156312/bdb81134-f693-11e5-889d-d56f99fed402.png)

**Comment by baronvonvaderham** [comment]
Yeah I'm going to need to restrict where we can drop that. Its alignment is dictated by the container it's being placed within. The Featured and Sponsors areas have very specific containers for those specific content types, we shouldn't be dropping text blocks into them.

Still working on that documentation and I'll also fix up the restrictions of what content can go where in the menus.

**Comment by jessicaaasheaashe** [comment]
Ok...but I will need to be able to put some text above those areas so what
is the solution?

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Wed, Mar 30, 2016 at 4:30 PM, Scott Johnson <notifications@github.com>
wrote:

> Yeah I'm going to need to restrict where we can drop that. Its alignment
> is dictated by the container it's being placed within. The Featured and
> Sponsors areas have very specific containers for those specific content
> types, we shouldn't be dropping text blocks into them.
>
> Still working on that documentation and I'll also fix up the restrictions
> of what content can go where in the menus.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/43#issuecomment-203620776>
>

-- 
Check out the new Campus Sustainability Hub <http://hub.aashe.org/>, an 
online library where members can quickly and easily find relevant resources.


Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by baronvonvaderham** [comment]
Is it just title headings you're adding? I can add a "Title" content type you can embed that will be centered and styled correctly.

**Comment by jessicaaasheaashe** [comment]
Yes...I'm just adding text to preface the content that is underneath in
those two instances.  Thanks!

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Wed, Mar 30, 2016 at 4:35 PM, Scott Johnson <notifications@github.com>
wrote:

> Is it just title headings you're adding? I can add a "Title" content type
> you can embed that will be centered and styled correctly.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/43#issuecomment-203623426>
>

-- 
Check out the new Campus Sustainability Hub <http://hub.aashe.org/>, an 
online library where members can quickly and easily find relevant resources.


Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by baronvonvaderham** [comment]
Ok, I'll have a new content type up for you tomorrow that lets you do that.

**Comment by jessicaaasheaashe** [comment]
Thanks Scott!

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Wed, Mar 30, 2016 at 4:37 PM, Scott Johnson <notifications@github.com>
wrote:

> Ok, I'll have a new content type up for you tomorrow that lets you do that.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/43#issuecomment-203624271>
>

-- 
Check out the new Campus Sustainability Hub <http://hub.aashe.org/>, an 
online library where members can quickly and easily find relevant resources.


Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>
