### ISSUE TITLE
Simple Layout Template & Keynote Content Type

### ISSUE THREAD

**Issue by jessicaaasheaashe** [AASHE/aashe-conference#47]
Can you make us a page for our keynotes like this: http://htmlstream.com/preview/unify-v1.8/page_about_our_team2.html

**Comment by baronvonvaderham** [comment]
Do you basically just want a 2 column layout with the banner at the top and a call to action at the bottom?

**Comment by baronvonvaderham** [comment]
I'm going to have to add a Keynote content type so that the two columns remain aligned. Otherwise we'll have a stack of text and images on each side with different heights.

Probably a good thing, I'll call it Keynote but we can use it for anything else that's two-column appropriate.

**Comment by jessicaaasheaashe** [comment]
I think so? I want it to look that page! LOL!  I will have three keynotes
and I would like to have a header image and then their bio and photo in
column format and be able to alternate which side the text/photo appears
for each one.



Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Thu, Mar 31, 2016 at 11:44 AM, Scott Johnson <notifications@github.com>
wrote:

> Do you basically just want a 2 column layout with the banner at the top
> and a call to action at the bottom?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/47#issuecomment-203992005>
>

-- 
Check out the new Campus Sustainability Hub <http://hub.aashe.org/>, an 
online library where members can quickly and easily find relevant resources.


Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by baronvonvaderham** [comment]
I'll have it up on heroku shortly, just about to test on my local machine. I made it as generic as possible so we can reuse it. There is an "orientation" selector that lets you choose if the image goes left or right. I didn't do anything with the text box, it's a flat RichText content type like you've been using so you can format it to your heart's content.
