### ISSUE TITLE
Image not appearing

### ISSUE THREAD

**Issue by jessicaaasheaashe** [AASHE/aashe-conference#49]
@baronvonvaderham I am editing the keynote page: http://aashe-conference-prod.herokuapp.com/program/keynotes/

In the title banner section, I added a static single banner content type and uploaded an image that I named "Keynote Page Banner Image" and then saved it.  However, that image is not dispaying on the page.  Can you look into this?

**Comment by baronvonvaderham** [comment]
Yes, it says in the documentation for that content type (and I've mentioned in a meeting) that those are currently broken until we solve an image serving issue. See Issue #1 and Issue #13.

**Comment by jessicaaasheaashe** [comment]
OK thanks...just wanted to make sure I wasn't doing something wrong.

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Thu, Mar 31, 2016 at 2:09 PM, Scott Johnson <notifications@github.com>
wrote:

> Yes, it says in the documentation for that content type (and I've
> mentioned in a meeting) that those are currently broken until we solve an
> image serving issue. See Issue #1
> <https://github.com/AASHE/aashe-conference/issues/1> and Issue #13
> <https://github.com/AASHE/aashe-conference/issues/13>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/49#issuecomment-204060014>
>

-- 
Check out the new Campus Sustainability Hub <http://hub.aashe.org/>, an 
online library where members can quickly and easily find relevant resources.


Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by baronvonvaderham** [comment]
Nope, you should be fine, if you leave the image in place once we fix the bug it should switch over automatically.

**Comment by jessicaaasheaashe** [comment]
OK thanks

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Thu, Mar 31, 2016 at 2:14 PM, Scott Johnson <notifications@github.com>
wrote:

> Nope, you should be fine, if you leave the image in place once we fix the
> bug it should switch over automatically.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/49#issuecomment-204061438>
>

-- 
Check out the new Campus Sustainability Hub <http://hub.aashe.org/>, an 
online library where members can quickly and easily find relevant resources.


Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>
