### ISSUE TITLE
Two Column Layout Text Box

### ISSUE THREAD

**Issue by jessicaaasheaashe** [AASHE/aashe-conference#51]
When entering text in the two column layout..the html tags are displaying: 

![image](https://cloud.githubusercontent.com/assets/18149121/14186747/d4d81e30-f74d-11e5-8b1c-510ce926b441.png)

**Comment by jessicaaasheaashe** [comment]
It is also not resizing the images:  http://aashe-conference-prod.herokuapp.com/program/keynotes/

**Comment by baronvonvaderham** [comment]
Fixed, pushing up to heroku now.

This has the same issue with trying to thumbnail images that I was experiencing with the Sponsor logos. They DO scale, they're class img-responsive, but they will fill the column to 100% width and scale height appropriately. So when you have a portrait aspect ratio instead of landscape, it expands the row severely.

Restricting it to a container like most other content helps mitigate this effect, but moving forward, I recommend choosing images for these regions carefully.....even if I could make them scale to fixed height, you'd then end up with these weird gray bars on either side of the pic and that's no good.

**Comment by jessicaaasheaashe** [comment]
Can you tell me what the region size is in width and height?  I can
resize/crop my portrait images in Photoshop to fit better to help here
too.  In this instance, I don't have a choice in photo orientation.  Thanks!

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Thu, Mar 31, 2016 at 4:29 PM, Scott Johnson <notifications@github.com>
wrote:

> Fixed, pushing up to heroku now.
>
> This has the same issue with trying to thumbnail images that I was
> experiencing with the Sponsor logos. They DO scale, they're class
> img-responsive, but they will fill the column to 100% width and scale
> height appropriately. So when you have a portrait aspect ratio instead of
> landscape, it expands the row severely.
>
> Restricting it to a container like most other content helps mitigate this
> effect, but moving forward, I recommend choosing images for these regions
> carefully.....even if I could make them scale to fixed height, you'd then
> end up with these weird gray bars on either side of the pic and that's no
> good.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/51#issuecomment-204112796>
>

-- 
Check out the new Campus Sustainability Hub <http://hub.aashe.org/>, an 
online library where members can quickly and easily find relevant resources.


Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by baronvonvaderham** [comment]
When the page is as large as it can go (when you start seeing the white space on either side of the content) the images will be 585 pixels wide. Any smaller than this and it will stretch out. Any larger and it will shrink. In both cases aspect ratio will be maintained.

**Comment by baronvonvaderham** [comment]
There's no absolute height dimension. I'd recommend seeing what looks best and scaling the others to match.
