### ISSUE TITLE
Schedule Overview page

### ISSUE THREAD

**Issue by jessicaaasheaashe** [AASHE/aashe-conference#52]
@baronvonvaderham Our "Schedule Overview" page will have content in it that would probably be best laid out in a table.  Can you create the ability for me to create a table to build our schedule overview page?  http://htmlstream.com/preview/unify-v1.8/shortcode_table_general.html  

Here is sample of the type of text that will go there: 

Sunday, Oct. 9, 2016
Registration Open 7:00 a.m. - 8:00 p.m.
Breakfast 7:30 a.m - 9:00 a.m.
Student Summit 8:30 a.m. - 4:30 p.m.
Student Summit Opening 8:30 a.m. - 9:45 a.m.
Coffee Break 9:45 a.m. - 10:00 a.m.
Student Workshops: 10:00 a.m. - 11:15 p.m.
Student Case Studies: 11:30-noon
Lunch 12:00 p.m. - 1:00 p.m.
Student Workshops 1:00 p.m. - 2:15 p.m.
Student Case Studies 2:30 - 3:00
Coffee Break 3:00 p.m. - 3:15 p.m.
Student Networking Sessions: 3:15 - 4:30
Pre-Conference Workshops
All Day 8:30 a.m. - 4:30 p.m. 
Morning Workshops 8:30 a.m. - 12:00 p.m.
Afternoon Workshops 1:00 p.m. - 4:30 p.m.
Academic Colloquia (Time?)
Opening Ceremony & Keynote 4:45 p.m. - 6:00 p.m.
Expo Hall Opening Reception 6:00 p.m. - 8:00 p.m.

Monday, Oct. 10, 2016
Registration Open 7:00 a.m. - 5:00 p.m.
Breakfast 7:30 a.m - 9:00 a.m.
Session A 8:15 a.m. - 8:45 a.m. CASE STUDIES
Session B 9:00 a.m. - 9:30 a.m. CASE STUDIES
Exhibits Open 9:30 a.m. - 4:30 p.m.
Coffee Break with Exhibitors 9:30 a.m. - 10:00 a.m. 
Session C 10:00 a.m. - 11:00 a.m. PANELS
Networking and Expo Time 11:00 a.m - 11:30 a.m.
Session D 11:30 a.m. - 12:00 p.m. CASE STUDIES 
Lunch with Exhibitors 12:00 p.m. - 2:00 p.m.
Networking Meetings 12:45 p.m. - 1:45 p.m.
Session E 2:00 p.m. - 3:00 p.m. PANELS
Sustainable Solutions Shark Tank 3:15-4:00 
Poster/Expo Session 4:00 p.m. - 5:15 p.m. with refreshments
Keynote Performance 5:30-6:30 p.m.
Evening Events 6:45 p.m. - 9:00 p.m.

**Comment by baronvonvaderham** [comment]
Yes, we're already working on this. It just isn't that easy to do. See Issue #31
