### ISSUE TITLE
Finalize Header Bar Links

### ISSUE THREAD

**Issue by jessicaaasheaashe** [AASHE/aashe-conference#54]
@baronvonvaderham can you link this page: http://aashe-conference-prod.herokuapp.com/about/
to the About tab in the top header menu?

**Comment by baronvonvaderham** [comment]
Absolutely, but let's hold off for the moment. I'd rather just do one big update once we finalize all of those links, less hectic that way.

**Comment by jessicaaasheaashe** [comment]
Can I create pages (that are blank), give you the URLs to update the menu and then add the content later?  Its helpful to see the page on the site as I'm building the page.

**Comment by baronvonvaderham** [comment]
Yes, that would be perfect, then I can take care of the entire header today.

**Comment by jessicaaasheaashe** [comment]
Sustainability Page: http://aashe-conference-prod.herokuapp.com/sustainability/
News & Media Page: http://aashe-conference-prod.herokuapp.com/news-media/

**Comment by jessicaaasheaashe** [comment]
That should be it!

**Comment by baronvonvaderham** [comment]
Do we want the Register link to point to just '/register/' here or to the cvent site or what?

**Comment by jessicaaasheaashe** [comment]
The register link will point to CVENT but I don't have that link yet and
probably won't for a while.

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Fri, Apr 1, 2016 at 1:53 PM, Scott Johnson <notifications@github.com>
wrote:

> Do we want the Register link to point to just '/register/' here or to the
> cvent site or what?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/54#issuecomment-204489650>
>

-- 
The AASHE Sustainability Awards are now open! Submit your application 
<http://www.aashe.org/about/aashe-awards> by Friday, June 3 at 5 p.m. ET.

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by baronvonvaderham** [comment]
Ok, I'll leave that as a null '#" for now.
