### ISSUE TITLE
Rich Text Editor Request

### ISSUE THREAD

**Issue by jessicaaasheaashe** [AASHE/aashe-conference#56]
Can we have the ability to format text in the rich text editor into a two column layout?  For example, I want to be able to put the bullet point lists on this page in two column to reduce some of the white space and page length: http://aashe-conference-prod.herokuapp.com/about/

I don't want to put the entire text in two columns though...only the bullet points.

**Comment by baronvonvaderham** [comment]
There's not really any way to accomplish this that I know of. However, you do now have table functionality.
