### ISSUE TITLE
TinyMCE Enhancement - Images

### ISSUE THREAD

**Issue by baronvonvaderham** [AASHE/aashe-conference#57]
Add functionality to embed images within RichText

**Comment by jessicaaasheaashe** [comment]
@jamstooks Hey Ben!  Any update on when you might get to this?  Its really jamming me up in completing any page with images in the Rich Text content type.

**Comment by jamstooks** [comment]
Hoping to get it done today... ran into a rabbit hole yesterday, but hoping I can figure it out today.

**Comment by jessicaaasheaashe** [comment]
Thanks for the update!

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Tue, Apr 19, 2016 at 10:55 AM, Benjamin W Stookey <
notifications@github.com> wrote:

> Hoping to get it done today... ran into a rabbit hole yesterday, but
> hoping I can figure it out today.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/57#issuecomment-211963198>
>

-- 
The AASHE Sustainability Awards are now open! Submit your application 
<http://www.aashe.org/about/aashe-awards> by Friday, June 3 at 5 p.m. ET. 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by jamstooks** [comment]
Spent a few hours on this tonight. It's a little more convoluted than I had hoped. I've made some strides though, so I'm hoping I can get back to this tomorrow afternoon to finish it up. I'll keep you posted.

**Comment by jamstooks** [comment]
I've added a pull request (#93) for this. We still need to go through and update the images that have already been added to rich text areas and will probably need to make some adjustments to the plugin I built, but this gets us started.

**Comment by baronvonvaderham** [comment]
Merged. Emailed Jessica to get her help tracking down images already in place that need to be modified.
