### ISSUE TITLE
Footer Styling Again

### ISSUE THREAD

**Issue by baronvonvaderham** [AASHE/aashe-conference#63]
Adding newsletter subscription link

**Comment by baronvonvaderham** [comment]
Amended requested wording to accommodate styling. Changed to "Newsletters" for header, "Subscribe Now" on the button. The other wording was far too long and no broke the layout of the footer.

**Comment by jessicaaasheaashe** [comment]
Works for me! Thanks!

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Mon, Apr 4, 2016 at 1:17 PM, Scott Johnson <notifications@github.com>
wrote:

> Amended requested wording to accommodate styling. Changed to "Newsletters"
> for header, "Subscribe Now" on the button. The other wording was far too
> long and no broke the layout of the footer.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/63#issuecomment-205400959>
>

-- 
Check out the new Campus Sustainability Hub <http://hub.aashe.org/>, an 
online library where members can quickly and easily find relevant resources.

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>
