### ISSUE TITLE
Page Template Requested for Registration Page

### ISSUE THREAD

**Issue by jessicaaasheaashe** [AASHE/aashe-conference#66]
@baronvonvaderham I would like to have a template with:

1) static banner image
2) rich text area or call to action bar with button link
3) this pricing table: http://htmlstream.com/preview/unify-v1.8/page_pricing_mega.html
4) rich text area

I would like this to create our registration and pricing page.  Please let me know if you can do this.  Thanks!

**Comment by baronvonvaderham** [comment]
That pricing table is not a template thing, that is an immensely complex new content type you're asking for. That's going to take some planning....

It will actually require multiple models to accomplish: Benefits Set (the row names), Pricing Levels (column names) would reference which of these are checked off (I would avoid having any with text, like they have on that example in the row "Subdomains").

The actual table would be the abstract type that you add to the page and select multiple Pricing Level objects.

**Comment by jessicaaasheaashe** [comment]
Should we wait then to see if a standard table design will work?  I want
our tables to have a little style to them and I think we have a separate
ticket for that.

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Tue, Apr 5, 2016 at 1:29 PM, Scott Johnson <notifications@github.com>
wrote:

> That pricing table is not a template thing, that is an immensely complex
> new content type you're asking for. That's going to take some planning....
>
> It will actually require multiple models to accomplish: Benefits Set (the
> row names), Pricing Levels (column names) would reference which of these
> are checked off (I would avoid having any with text, like they have on that
> example in the row "Subdomains").
>
> The actual table would be the abstract type that you add to the page and
> select multiple Pricing Level objects.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/66#issuecomment-205908983>
>

-- 
The AASHE Sustainability Awards are now open! Submit your application 
<http://www.aashe.org/about/aashe-awards> by Friday, June 3 at 5 p.m. ET. 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by baronvonvaderham** [comment]
No this requires a new content type to get that to work, it's just not going to be one I fire off in half an hour like the others have been, there's a lot of complex data relations to account for.

**Comment by baronvonvaderham** [comment]
It's coming along....

screenshot

I am just having some inexplicable difficulty passing the data for the 
levels into the template so the name, price, and the X or check is done 
correctly.

**Comment by jessicaaasheaashe** [comment]
@baronvonvaderham Hey...was there supposed to be a screenshot?  All I see is the word "screenshot".

**Comment by baronvonvaderham** [comment]
Oh, it filtered out the image. Not important.

**Comment by baronvonvaderham** [comment]
Done! Just need to test it out on dev. This one was an absolute beast, but I learned some new stuff about ManyToMany data relations inside FeinCMS abstract models.

**Comment by baronvonvaderham** [comment]
Seems to be ok, now I guess I need to circle back and make the originally requested template to embed this in.

**Comment by baronvonvaderham** [comment]
Here we go! http://conference-dev.herokuapp.com/register/

Pushing it up into production right now, let me know if you need me to walk you through creating one.

**Comment by jessicaaasheaashe** [comment]
Yep....I think I need you to walk me through it.  I can hop on a Google chat any time today...let me know what works for you.

**Comment by baronvonvaderham** [comment]
Sure, let me boot up my laptop so hopefully I can use skype in Windows and share my screen better.

**Comment by jessicaaasheaashe** [comment]
Ok thanks!

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Wed, Apr 6, 2016 at 11:34 AM, Scott Johnson <notifications@github.com>
wrote:

> Sure, let me boot up my laptop so hopefully I can use skype in Windows and
> share my screen better.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/66#issuecomment-206432547>
>

-- 
The AASHE Sustainability Awards are now open! Submit your application 
<http://www.aashe.org/about/aashe-awards> by Friday, June 3 at 5 p.m. ET. 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>
