### ISSUE TITLE
Add Table Content Type

### ISSUE THREAD

**Issue by jessicaaasheaashe** [AASHE/aashe-conference#67]
I used a table to create our "Schedule-at-a-Glance page.  Could you help add a little styling so it displays better?  The first table on this Unfiy template looks nice and I was thinking we could use our AASHE green as an accent color: http://htmlstream.com/preview/unify-v1.8/shortcode_table_general.html  

I also, like the striped rows to help differentiate the rows better.

**Comment by baronvonvaderham** [comment]
I'll see what I can do.

**Comment by baronvonvaderham** [comment]
Unfortunately that's not possible, TinyMCE creates all of the HTML and it has no unique identifiers to attach CSS class modifications to.

This needs to be another content type.

**Comment by baronvonvaderham** [comment]
Figured it out. You'll have a "Rich Text Table Block" content type available that gives you 3 fields: Title, header block, and table (can't get the labels on the last two to show up). Header block is optional, just the text you see between the title bar and the top of your table.

Table is restyled to inherit peroperties from Unify. You might want to tweak your table to change things around (it expands your table to fill the space).

It should fit wherever, so it will be accessible anywhere RichText is.
