### ISSUE TITLE
Table Alignment Issue on Exhibitor List Page

### ISSUE THREAD

**Issue by jessicaaasheaashe** [AASHE/aashe-conference#69]
@baronvonvaderham I created a table on this page: http://aashe-conference-prod.herokuapp.com/expo-hall/exhibitor-list-floor-plan/

which I would like to wrap/align next to the image of the floor plan.  Currently, it is underneath it.  Could you help me fix?  

Thanks!

**Comment by baronvonvaderham** [comment]
That page no longer exists so I can't troubleshoot.

I recommend waiting on this as Ben is supposed to solve the issue of embedding images within RichText, but he's out on vacation. When he solves that, then you can probably achieve this within a table.

Alternatively, you could also try one of the templates with the two column regions, placing the table in the left column and the image in the right. If you want to center what ends up under the image, you can move that piece into a region below it with another richtext item.

**Comment by jessicaaasheaashe** [comment]
New URL: 
http://aashe-conference-prod.herokuapp.com/expo-hall/exhibitor-list/

I can try the two column regions...

**Comment by jessicaaasheaashe** [comment]
FYI...I tried the two column template and that didn't work either:

http://aashe-conference-prod.herokuapp.com/test-page/

I will wait for Ben.   Thanks!

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Tue, Apr 5, 2016 at 11:54 AM, Scott Johnson <notifications@github.com>
wrote:

> That page no longer exists so I can't troubleshoot.
>
> I recommend waiting on this as Ben is supposed to solve the issue of
> embedding images within RichText, but he's out on vacation. When he solves
> that, then you can probably achieve this within a table.
>
> Alternatively, you could also try one of the templates with the two column
> regions, placing the table in the left column and the image in the right.
> If you want to center what ends up under the image, you can move that piece
> into a region below it with another richtext item.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/69#issuecomment-205867865>
>

-- 
The AASHE Sustainability Awards are now open! Submit your application 
<http://www.aashe.org/about/aashe-awards> by Friday, June 3 at 5 p.m. ET. 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by jessicaaasheaashe** [comment]
I ended up changing the page layout so the table alignment on this page is no longer an issue but I do still have the problem with the image not displaying on the page.

**Comment by baronvonvaderham** [comment]
Ok cool. Ben is working on that in Issue #57
