### ISSUE TITLE
Force Banner Images to remain centered

### ISSUE THREAD

**Issue by baronvonvaderham** [AASHE/aashe-conference#74]

**Comment by baronvonvaderham** [comment]
Good news @jessicaaasheaashe! Found a way to auto-scale the banner image after all with some CSS trickery. Now you just need to crop it to the right aspect ratio.

**Comment by jessicaaasheaashe** [comment]
Awesome...let me know when that is set up and I will give a try.

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Wed, Apr 6, 2016 at 4:22 PM, Scott Johnson <notifications@github.com>
wrote:

> Good news @jessicaaasheaashe <https://github.com/jessicaaasheaashe>!
> Found a way to auto-scale the banner image after all with some CSS
> trickery. Now you just need to crop it to the right aspect ratio.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/74#issuecomment-206543098>
>

-- 
The AASHE Sustainability Awards are now open! Submit your application 
<http://www.aashe.org/about/aashe-awards> by Friday, June 3 at 5 p.m. ET. 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by baronvonvaderham** [comment]
Should be up

**Comment by jessicaaasheaashe** [comment]
Ok cool! Thanks!

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Wed, Apr 6, 2016 at 4:35 PM, Scott Johnson <notifications@github.com>
wrote:

> Should be up
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/74#issuecomment-206552219>
>

-- 
The AASHE Sustainability Awards are now open! Submit your application 
<http://www.aashe.org/about/aashe-awards> by Friday, June 3 at 5 p.m. ET. 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by baronvonvaderham** [comment]
Small update being pushed up that centers the image vertically if it's too tall.
