### ISSUE TITLE
Topic Area Template - Featured Pane and Title Box Layout

### ISSUE THREAD

**Issue by jessicaaasheaashe** [AASHE/aashe-conference#78]
@baronvonvaderham The last featured pane and the title box is not aligning properly on the News & Media page: 

![image](https://cloud.githubusercontent.com/assets/18149121/14327386/0efc0962-fc00-11e5-855f-e7bc8f4793f5.png)

**Comment by baronvonvaderham** [comment]
Is this still happening?

**Comment by jessicaaasheaashe** [comment]
Yes, please see screenshot:

[image: Inline image 1]

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Wed, Apr 6, 2016 at 6:18 PM, Scott Johnson <notifications@github.com>
wrote:

> Is this still happening?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/78#issuecomment-206593652>
>

-- 
The AASHE Sustainability Awards are now open! Submit your application 
<http://www.aashe.org/about/aashe-awards> by Friday, June 3 at 5 p.m. ET. 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by jessicaaasheaashe** [comment]
I tried to rearrange the panes in the content area but that didn't fix it either: 

![image](https://cloud.githubusercontent.com/assets/18149121/14350479/7cffe09a-fc97-11e5-8a2f-68b5bf85f443.png)

**Comment by baronvonvaderham** [comment]
Fixed. The Topic Page template will now contain two separate regions for these panes, supporting 2 per region for up to 4 panes. If we need more, we will need to add more regions.....it was a weird styling thing. These divs need to be grouped into pairs inside a "row" class or else stuff breaks. Not ideal, but it should work.

**Comment by baronvonvaderham** [comment]
Oh I also removed the buttons. The URL now turns the title of the pane into a link. There's still a "button text" field, but it's not used....I'll find a way to remove it some time, but it was easier to leave it in place for now. Just leave it blank.
