### ISSUE TITLE
Schedule at a Glance page table alignment

### ISSUE THREAD

**Issue by jessicaaasheaashe** [AASHE/aashe-conference#80]
@baronvonvaderham I ended up creating separate tables for each day for the Schedule-at-a Glance page.  However, now the columns widths do not match up for each table.  I set each table to be the same width but that didn't help.  Could you help?   I can't seem to specify column width for a table.

**Comment by baronvonvaderham** [comment]
You can select all cells in that column and manually specify the width. Doing that for the first column of the second table (choosing the value from looking at the other tables in the rendered page to see those were 737px wide) fixed it.

If you have your table selected (or a row or column or cell) the table menu has options like this for you.

**Comment by jessicaaasheaashe** [comment]
Thank you!

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Wed, Apr 6, 2016 at 3:41 PM, Scott Johnson <notifications@github.com>
wrote:

> You can select all cells in that column and manually specify the width.
> Doing that for the first column of the second table (choosing the value
> from looking at the other tables in the rendered page to see those were
> 737px wide) fixed it.
>
> If you have your table selected (or a row or column or cell) the table
> menu has options like this for you.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/80#issuecomment-206528055>
>

-- 
The AASHE Sustainability Awards are now open! Submit your application 
<http://www.aashe.org/about/aashe-awards> by Friday, June 3 at 5 p.m. ET. 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>
