### ISSUE TITLE
Images not appearing 

### ISSUE THREAD

**Issue by jessicaaasheaashe** [AASHE/aashe-conference#82]
The images are not appearing on this page: 

http://aashe-conference-prod.herokuapp.com/expo-hall/sponsors-host-institutions/

and this page: 

http://aashe-conference-prod.herokuapp.com/expo-hall/exhibitor-list/

**Comment by baronvonvaderham** [comment]
Hmmm, when did the editor start showing an image embed option? This is going to be redundant to Issue #57, it's the same error I encountered with trying to use the thumbnail package for image resizing.
