### ISSUE TITLE
gallery page

### ISSUE THREAD

**Issue by jessicaaasheaashe** [AASHE/aashe-conference#83]
Add ability to add embedded YouTube video and additional Flickr galleries.  The page needs some styling...they are raw text content currently stacks on top of each other.  I think we talked about a three column grid with the ability to add title boxes between rows.

**Comment by baronvonvaderham** [comment]
So the solution is actually inside the raw content pieces themselves. Quick bootstrap boot camp: it uses a 12 column layout. If you look in the raw content, I wrapped these object code chunks in div tags, with class col-md-6. This means it's a 6 column div, or half the width of the container. This gives you a nice 2 column layout. For 3 columns, you wrap each in a col-md-4.

Also needed was style="display:inline-block;" within the opening div tag. This tells the browser to render them in the same row, as many as can fit (if you go over 12 total columns, say you have a 6-4-4, it will wrap onto the next line after that).

Lastly, within the object code, you'll see two places that specify height and width, one near the top and one at the very end. I modified both of these to scale them to a 450 pixel width. This made them fit within half the container (1140 max width, so each column is 570 wide) with some padding between. You can tweak these as you like, just bear in mind that max width and how many columns you have, and use your math to keep the aspect ratio the same (the original was 600 by 450, so 450/600=0.75....then if I want it 450 wide, I multiply 450 x 0.75 to get a height of 338 pixels).

Sorry, I know that's a lot of info, but just shoot me an email if you get confused.

On top of that, I'll be pushing up a modified template that adds a region for youtube videos below this that will align them to a nice grid.

**Comment by jessicaaasheaashe** [comment]
I'm not sure if I created this page correctly: http://aashe-conference-prod.herokuapp.com/about/gallery/. 

Is it possible to add a rich text content type before the Flickr content type so I can add a little intro text?

**Comment by baronvonvaderham** [comment]
I'll add a rich text region, but otherwise yes, that works. Just a note there is a youtube video content type available in the youtube videos section that auto-aligns them for you.

**Comment by jessicaaasheaashe** [comment]
I tried the YouTube video and it just dropped a link on the page, it didn't embed.

**Comment by baronvonvaderham** [comment]
Oh it's because you were trying to embed an entire playlist link (https://youtu.be/1VHHRrR4wWo?list=PLkWouUMH8JRH1QgAuUsk3UjKVJIkg6LkS) rather than individual video links. For the entire playlist you did the right thing, an iframe embed works there. I will add a col-md-6 class wrapper around it just in case, but otherwise that's fine.
