### ISSUE TITLE
Sorl-thumbnail integration

### ISSUE THREAD

**Issue by baronvonvaderham** [AASHE/aashe-conference#84]
Fix bug with thumbnails returning 403 forbidden errors and being unable to write to S3 to store new files.

**Comment by jamstooks** [comment]
The problem itself has been fixed. We had to use the image.file.url, not just image.file in the template tag. I've only fixed three of the content types though in my commit: 09896fc

**Comment by jamstooks** [comment]
I'll leave the rest of the content types to you, @baronvonvaderham.

**Comment by baronvonvaderham** [comment]
Confirmed works perfectly, going through and modifying the remaining image content types.
