### ISSUE TITLE
Hover text not working

### ISSUE THREAD

**Issue by jessicaaasheaashe** [AASHE/aashe-conference#85]
On this page: http://aashe-conference-prod.herokuapp.com/registration/registration-fees/#

I did change the page title and placement on the menu but that is all I have changed today.

**Comment by baronvonvaderham** [comment]
Ah, yeah that's a bug from compression, it isn't loading the JS I need for that correctly. Should be a simple fix.

**Comment by baronvonvaderham** [comment]
Fixed!

**Comment by jessicaaasheaashe** [comment]
This still seems to be an issue for me.

**Comment by baronvonvaderham** [comment]
Script was accidentally deleted in the rigamarole of debugging the other compression nonsense.
