### ISSUE TITLE
Feature Panes for Topic Pages

### ISSUE THREAD

**Issue by jessicaaasheaashe** [AASHE/aashe-conference#92]
@baronvonvaderham I just realized that I am using "feature panes" each of the main menu landing pages to provide links/access to the subpages in the rest of that section.  In the programs section, we will have 11 (and possibly up to 14) different subpages but we only have two rows (or 4 panes) available.  Could you add more to accommodate this type of use?

**Comment by baronvonvaderham** [comment]
While I'm in here do you need more icons?

**Comment by jessicaaasheaashe** [comment]
Yes but I need to pick them out.

**Comment by jessicaaasheaashe** [comment]
I will probably need different ones for each subpage.

**Comment by baronvonvaderham** [comment]
Just get me a list of them and I'll add in the options.

**Comment by jessicaaasheaashe** [comment]
Will do once I have created all of the menu landing pages we will go through and find the right icons for each one.  Thanks!

**Comment by baronvonvaderham** [comment]
Alright, I guess open a new ticket when you get to that, I just want to close this one out since the fix is done.

**Comment by jessicaaasheaashe** [comment]
@baronvonvaderham I don't see the fix for the original issue?

**Comment by baronvonvaderham** [comment]
Admin seems to be glitching out due to the change. Not sure why. I'll have to dig into this more tomorrow.

**Comment by baronvonvaderham** [comment]
This breaks in production because there is too much stuff already loaded into the database table that manages the pages and the regions they contain (this is why it's a bad idea to make major feature changes so late in the game). I'm going to have to completely revamp how this content type works so it can be rendered in a single region rather than having to have a region for each row.

**Comment by jessicaaasheaashe** [comment]
Or is this there a different content type/template that we can add that
will have a similar result?

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Thu, Apr 21, 2016 at 12:44 PM, Scott Johnson <notifications@github.com>
wrote:

> This breaks in production because there is too much stuff already loaded
> into the database table that manages the pages and the regions they contain
> (this is why it's a bad idea to make major feature changes so late in the
> game). I'm going to have to completely revamp how this content type works
> so it can be rendered in a single region rather than having to have a
> region for each row.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/92#issuecomment-213006734>
>

-- 
The AASHE Sustainability Awards are now open! Submit your application 
<http://www.aashe.org/about/aashe-awards> by Friday, June 3 at 5 p.m. ET. 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by baronvonvaderham** [comment]
Not that wouldn't have this layout issue, no.

Just switching this over to behave more like the Logo Ticker. You'll have an abstract content type "Featured Pane Set" from which you'll choose which panes to display. Not ideal, but it'll work. Modifying the existing pane content type to be non-abstract and it'll add a name field so you can title the panes to tell them apart in the selection menu.

**Comment by jessicaaasheaashe** [comment]
There are these ICON Boxes that could basically the same thing I'm trying
to accomplish: http://wrapbootstrap.com/preview/WB0412697

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Thu, Apr 21, 2016 at 12:44 PM, Scott Johnson <notifications@github.com>
wrote:

> This breaks in production because there is too much stuff already loaded
> into the database table that manages the pages and the regions they contain
> (this is why it's a bad idea to make major feature changes so late in the
> game). I'm going to have to completely revamp how this content type works
> so it can be rendered in a single region rather than having to have a
> region for each row.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/92#issuecomment-213006734>
>

-- 
The AASHE Sustainability Awards are now open! Submit your application 
<http://www.aashe.org/about/aashe-awards> by Friday, June 3 at 5 p.m. ET. 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by baronvonvaderham** [comment]
Same layout issue. They require being wrapped in row classes by groups.

Actually, I'm going to go back and troubleshoot the original problem that necessitated the separate rows. I still feel like that shouldn't even be necessary, there has to be something glitching in the CSS somewhere.

**Comment by jessicaaasheaashe** [comment]
Thanks Scott!

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Thu, Apr 21, 2016 at 12:54 PM, Scott Johnson <notifications@github.com>
wrote:

> Same layout issue. They require being wrapped in row classes by groups.
>
> Actually, I'm going to go back and troubleshoot the original problem that
> necessitated the separate rows. I still feel like that shouldn't even be
> necessary, there has to be something glitching in the CSS somewhere.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/92#issuecomment-213013180>
>

-- 
The AASHE Sustainability Awards are now open! Submit your application 
<http://www.aashe.org/about/aashe-awards> by Friday, June 3 at 5 p.m. ET. 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by baronvonvaderham** [comment]
Found the problem. This has to be deployed in three stages since this is on the production environment with existing content:

1) I deploy the fix, along with a new region that's just "Featured".
2) You migrate your panes from the row regions over to this one (remember at the bottom of the block there's an option to move it that appears if you mouse over the area).
3) Once that's done, I deploy again to remove those row regions from the template.

If I just pushed up the whole thing at once you'd lose all of that content since the regions they're registered to would no longer exist.

**Comment by jessicaaasheaashe** [comment]
OK...let me know when can move my panes.  I have some calls and other
priorities for next couple hours but should be able to do it late this
afternoon and let you know when I'm finished.  I think I only have them set
up in 2 or 3 pages right now so it shouldn't take me long to move.



Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Thu, Apr 21, 2016 at 1:10 PM, Scott Johnson <notifications@github.com>
wrote:

> Found the problem. This has to be deployed in three stages since this is
> on the production environment with existing content:
>
> 1) I deploy the fix, along with a new region that's just "Featured".
> 2) You migrate your panes from the row regions over to this one (remember
> at the bottom of the block there's an option to move it that appears if you
> mouse over the area).
> 3) Once that's done, I deploy again to remove those row regions from the
> template.
>
> If I just pushed up the whole thing at once you'd lose all of that content
> since the regions they're registered to would no longer exist.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/92#issuecomment-213021552>
>

-- 
The AASHE Sustainability Awards are now open! Submit your application 
<http://www.aashe.org/about/aashe-awards> by Friday, June 3 at 5 p.m. ET. 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by baronvonvaderham** [comment]
Ok that works, no rush. Stage 1's being deployed right now, should be up in a couple minutes (this thing has gotten so large it takes about 4 minutes to deploy into the dev sever, then another minute to move that through the deployment pipeline to staging and finally prod). Let me know when you've migrated the panes and I'll have the last piece ready to go.

**Comment by jessicaaasheaashe** [comment]
I can't seem to get the pages I need to load on the admin side in order to
edit them.  I have been trying to edit the "registration" page and it keeps
getting hung up.

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Thu, Apr 21, 2016 at 1:14 PM, Scott Johnson <notifications@github.com>
wrote:

> Ok that works, no rush. Stage 1's being deployed right now, should be up
> in a couple minutes (this thing has gotten so large it takes about 4
> minutes to deploy into the dev sever, then another minute to move that
> through the deployment pipeline to staging and finally prod). Let me know
> when you've migrated the panes and I'll have the last piece ready to go.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/92#issuecomment-213022676>
>

-- 
The AASHE Sustainability Awards are now open! Submit your application 
<http://www.aashe.org/about/aashe-awards> by Friday, June 3 at 5 p.m. ET. 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by baronvonvaderham** [comment]
Oh, accidentally left in the 7 row layout. That's the thing that breaks the admin that precipitated all of this in the first place. Need to re-push to remove it.

**Comment by baronvonvaderham** [comment]
Ok you're back up

**Comment by jessicaaasheaashe** [comment]
thanks

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Thu, Apr 21, 2016 at 3:41 PM, Scott Johnson <notifications@github.com>
wrote:

> Ok you're back up
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/92#issuecomment-213084296>
>

-- 
The AASHE Sustainability Awards are now open! Submit your application 
<http://www.aashe.org/about/aashe-awards> by Friday, June 3 at 5 p.m. ET. 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by jessicaaasheaashe** [comment]
Ok...I have moved them all to the featured content area but that seems to
have messed up the alignment on the News & Media page.

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Thu, Apr 21, 2016 at 1:14 PM, Scott Johnson <notifications@github.com>
wrote:

> Ok that works, no rush. Stage 1's being deployed right now, should be up
> in a couple minutes (this thing has gotten so large it takes about 4
> minutes to deploy into the dev sever, then another minute to move that
> through the deployment pipeline to staging and finally prod). Let me know
> when you've migrated the panes and I'll have the last piece ready to go.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/92#issuecomment-213022676>
>

-- 
The AASHE Sustainability Awards are now open! Submit your application 
<http://www.aashe.org/about/aashe-awards> by Friday, June 3 at 5 p.m. ET. 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by baronvonvaderham** [comment]
Yes, it's going to be messed up until I push up the new modified template.

**Comment by baronvonvaderham** [comment]
Should be fixed now. Had to leave in a region for these if you are using two types of pane together one after the other. For some reason that glitches out the first item of the second kind of pane.
