### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by jessicaaasheaashe** [AASHE/aashe-conference#95]
@baronvonvaderham @jamstooks I'm not sure if you guys will see this over the weekend but I am getting an "application error" which is preventing me from editing the site: 

![image](https://cloud.githubusercontent.com/assets/18149121/14768307/b5b4236a-0a0c-11e6-9548-77d819eb7889.png)

**Comment by jessicaaasheaashe** [comment]
Seems to be working now.

**Comment by baronvonvaderham** [comment]
Yeah might have been a database error or something, temporarily one-off glitch.
