### ISSUE TITLE
Drop-down menu link redundancy

### ISSUE THREAD

**Issue by baronvonvaderham** [AASHE/aashe-conference#96]
Popular critique from staff was that it was strange to have a menu item, e.g. "About", but it was not clickable, one had to instead hover to open the menu and select "About" at the top of the drop-down's contents.

**Comment by baronvonvaderham** [comment]
I found a handy package: https://github.com/mliu7/django-minidetector/

This adds a simple middleware class that adds some toggle variables to the request object, the most important for my purposes being "is_touch_device".

This allowed me to add conditional branches to the menu construction. So the pseudo-code becomes....

Loop through parent pages
If touch device{
  link target is href="javascript:void(0);"
  add page's url as top item of dropdown menu
}
else{
  link target is page's url
  no link in dropdown
}
loop through subpages to populate the menu as normal

The end result is two different presentations of the menu for mobile vs desktop, solving the issue of the weird redundancy, making desktop hover-only, while also preserving click-to-open functionality on mobile devices.

**Comment by jessicaaasheaashe** [comment]
This is awesome! Thanks!

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Mon, Apr 25, 2016 at 4:24 PM, Scott Johnson <notifications@github.com>
wrote:

> I found a handy package: https://github.com/mliu7/django-minidetector/
>
> This adds a simple middleware class that adds some toggle variables to the
> request object, the most important for my purposes being "is_touch_device".
>
> This allowed me to add conditional branches to the menu construction. So
> the pseudo-code becomes....
>
> Loop through parent pages
> If touch device{
> link target is href="javascript:void(0);"
> add page's url as top item of dropdown menu
> }
> else{
> link target is page's url
> no link in dropdown
> }
> loop through subpages to populate the menu as normal
>
> The end result is two different presentations of the menu for mobile vs
> desktop, solving the issue of the weird redundancy, making desktop
> hover-only, while also preserving click-to-open functionality on mobile
> devices.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/96#issuecomment-214509366>
>

-- 
The AASHE Sustainability Awards are now open! Submit your application 
<http://www.aashe.org/about/aashe-awards> by Friday, June 3 at 5 p.m. ET. 

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>
