### ISSUE TITLE
Exhibitor list page

### ISSUE THREAD

**Issue by jessicaaasheaashe** [AASHE/aashe-conference#98]
@baronvonvaderham I added a double link button to this page and remove the embedded floor plan image I had to try and improve the page layout.  The buttons seem squished in between the Expo Hall hours and the exhibitor list table which are in two different content areas/types so I don't know how to add some space to make it look better.  Could you take a look: http://aashe-conference-prod.herokuapp.com/expo-hall/exhibitor-list/

Thanks!

**Comment by baronvonvaderham** [comment]
Just need some padding below the buttons content type.
